### ISSUE TITLE
RuntimeError: Could not open file model/yolov3.caffemodel

### ISSUE THREAD

**Issue by pedrombmachado** [jasonlovescoding/YOLOv3-caffe#3]
Hi @jasonlovescoding ,
   I got the following error when I was trying to run the command
```
$ python3 detect_one.py --image=images/dog-cycle-car.png
```

> WARNING: Logging before InitGoogleLogging() is written to STDERR 
> W0820 15:32:32.210172 22688 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
> W0820 15:32:32.210202 22688 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
> W0820 15:32:32.210206 22688 _caffe.cpp:142] Net('model/yolov3.prototxt', 1, weights='model/yolov3.caffemodel')
> Traceback (most recent call last):
>  File "detect_one.py", line 60, in <module>
>   main()
>  File "detect_one.py", line 20, in main
>   model = caffe.Net(args.prototxt, args.caffemodel, caffe.TEST)
> RuntimeError: Could not open file model/yolov3.caffemodel

**Comment by pedrombmachado** [comment]
Dorted! I was missing the model!
